autoconf_url: http://ftp.gnu.org/gnu/autoconf/autoconf-2.69.tar.gz
autoconf_archive_url: http://gnu.mirror.constant.com/autoconf-archive/autoconf-archive-2019.01.06.tar.xz
leptonica_url: http://leptonica.org/source/leptonica-1.77.0.tar.gz
tesseract_url: https://github.com/tesseract-ocr/tesseract/archive/4.0.0.tar.gz

# Compile options
CC: /opt/rh/devtoolset-7/root/usr/bin/gcc
CXX: /opt/rh/devtoolset-7/root/usr/bin/c++